title: Commenting on Issues
tagline: Learn how to comment on an issue
description: Point users to a newly created issue and closes the original issue
template:
  name: commenting-on-issues
  repo: Test
