title: Course #1
tagline: [Tagline]
description: [Description]
template:
  name: commenting-on-issues
  repo: my_secret_repo
steps:
  - title: Comment on an issue
    event: issue_comment.created
    actions:
      - type: createIssue
        title: New Issue
        body: README.md
        # Store the response for this new issue by assigning an action_id
        action_id: new_issue

        # Close the issue the user just commented on
      - type: closeIssue

        # Respond in the issue the user just commented on
      - type: respond
        with: README.md
        # Include a `data` object to provide some template variables
        data:
          # Reference the response of the `new_issue` action
          nextIssueUrl: '%actions.new_issue.data.html_url%'
